apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
    project: expense
  ports:
    protocol: TCP
    port: 80
    target port: {{ .Values.configmap.port }}
    nodeport: {{ .Values.service.port }}
